### ISSUE TITLE
"RestGraphDatabase" can not  work with tinkerpop blueprints "Neo4jGraph"

### ISSUE THREAD

**Issue by zerofor** [neo4j-contrib/java-rest-binding#36]
hi, all, I am recently  using tinkerpop blueprints stack as RDF triple store engine, and i try java-rest-binding  api like this:

GraphDatabaseService ds = new RestGraphDatabase("http://localhost:7474/db/data");
Neo4jGraph graph = new Neo4jGraph(ds);    //blueprints.impls.neo4j.Neo4jGraph

pop up a exception:
Exception in thread "main" java.lang.ClassCastException: org.neo4j.rest.graphdb.RestGraphDatabase cannot be cast to org.neo4j.kernel.InternalAbstractGraphDatabase

it seems "RestGraphDatabase" is not a subclass of  "InternalAbstractGraphDatabase", is  there any chance that i can work around this exception , so that i can reuse the whole blueprints stack for rdf  sail processing ~

**Comment by rash805115** [comment]
@zerofor Can you post your code. I am trying to do the same stuff, but just cannot get it to work.

**Comment by jexp** [comment]
We removed gremlin support for this a while ago as the gremlin plugin is no longer published with Neo4j by default. 

Please note that this library will be sunset soon.

**Comment by rash805115** [comment]
So if gremlin support is removed, then can you point me as to how to have gremlin with neo4j over rest in java ? (I can easily integrate gremlin over embedded mode). Are there some other APIs that do this. Is tinkerpop coming up with something?

Just FYI: I am using version 2.0.1 of this library.
