### ISSUE TITLE
char[] stored as string

### ISSUE THREAD

**Issue by craigryan** [neo4j-contrib/java-rest-binding#80]
```
graphdb = new RestGraphDatabase(..)
char[] charArr = {'a', 'b', 'c'};
Node n = graphdb.createNode(lab);
n.setProperty("charArr", charArr);

```

Examining the graph, charArr is stored as a String instead of [a, b, c]. The workaround is to use a list:

```
List<Character> listChars= Arrays.asList('a', 'b', 'c');
n.setProperty("charArr", listChars);
```

 but char[] should work and other simple array types are stored correctly.

**Comment by jexp** [comment]
It's probably how char[] are encoded in JSON, not much we can do.

Also please note that this library is no longer maintained, it was never a good idea to pretend to be a GraphDatabaseAPI over the wire.
